name: Build & Deploy
run-name: Build & Deploy ${{ github.repository }}

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy landing page to gh-pages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@394d78e5b40cc35c170eb909b1f81551f37feb05 # v2.5.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5 # v3.5.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@f97b83114c6f41cfaa57698147ad3ce20543a127 # v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install and upgrade PIP
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: >
          pip install
          mkdocs
          mkdocs-material

      - name: Build & Deploy
        run: |
          git config --global user.name ${user_name}
          git config --global user.email ${user_email}
          git remote set-url origin https://${github_token}@github.com/${github_repository}
          mkdocs gh-deploy

        env:
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.SEYLUBOT_PAT}}
          github_repository: ${{ github.repository }}
