name: Build & Deploy
run-name: Build & Deploy ${{ github.repository }}

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy landing page to gh-pages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@394d78e5b40cc35c170eb909b1f81551f37feb05 # v2.5.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v3.5.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install and upgrade PIP
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install mkdocs-material

      - name: Build & Deploy
        run: mkdocs gh-deploy --force
